[2025-02-12T10:02:44.791+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-12T10:02:44.844+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_sellers manual__2025-02-12T10:01:53.320861+00:00 [queued]>
[2025-02-12T10:02:44.864+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_sellers manual__2025-02-12T10:01:53.320861+00:00 [queued]>
[2025-02-12T10:02:44.866+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-12T10:02:44.902+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_sellers> on 2025-02-12 10:01:53.320861+00:00
[2025-02-12T10:02:44.912+0000] {standard_task_runner.py:63} INFO - Started process 326 to run task
[2025-02-12T10:02:44.918+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform.transform_dim_sellers', 'manual__2025-02-12T10:01:53.320861+00:00', '--job-id', '264', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmpfimhwrj1']
[2025-02-12T10:02:44.923+0000] {standard_task_runner.py:91} INFO - Job 264: Subtask transform.transform_dim_sellers
[2025-02-12T10:02:45.020+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform.transform_dim_sellers manual__2025-02-12T10:01:53.320861+00:00 [running]> on host 0cefc44a17d0
[2025-02-12T10:02:45.202+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform.transform_dim_sellers' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T10:01:53.320861+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T10:01:53.320861+00:00'
[2025-02-12T10:02:45.204+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-12T10:02:45.525+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T10:02:45.766+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T10:02:45.946+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T10:02:46.179+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-12T10:02:46.476+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T10:02:47.277+0000] {logging_mixin.py:188} INFO - Đã transform và lưu dữ liệu vào dim_sellers
[2025-02-12T10:02:47.288+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-02-12T10:02:47.291+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-12T10:02:47.322+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=transform.transform_dim_sellers, run_id=manual__2025-02-12T10:01:53.320861+00:00, execution_date=20250212T100153, start_date=20250212T100244, end_date=20250212T100247
[2025-02-12T10:02:47.411+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-12T10:02:47.481+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T10:02:47.486+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
